version: '3.7'

services:
  container-mesh-marketplace:
    image: ghcr.io/geodis-tmoreau/container-mesh-marketplace:main
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.services.marketplace.loadbalancer.server.port=80
      - traefik.http.routers.marketplace.entrypoints=https
      - traefik.http.routers.marketplace.rule=Host(`marketplace.containermesh.onerecord.fr`)

networks:
  traefik:
    external: true
    name: onerecord-traefik